import type { ReactElement } from 'react'
import { useEffect, useMemo, useState } from 'react'
import Head from 'next/head'
import { Box, Flex, Text } from 'components'
import { AdminGuard } from 'components/admin-guard'
import { AdminShell } from 'layout/admin-shell'
import { readCertificationTemplates, saveCertificationTemplates } from 'certification-templates'
import type { CertificationTemplate } from 'certification-templates'

import type { NextPageWithLayout } from '../_app'

const uid = (): string => `cert-template-${Date.now()}-${Math.random().toString(16).slice(2)}`
const empty = (): CertificationTemplate => ({ id: uid(), name: '', equipment: '', hours: 8, equipmentBrand: '', limitedUse: '', validity: '1 año', contactInfo: 'HM Maquinaria · 304 242 5384', description: '', active: true })
const Page: NextPageWithLayout = () => {
  const [items, setItems] = useState<CertificationTemplate[]>([])
  const [editing, setEditing] = useState<CertificationTemplate | null>(null)
  const [search, setSearch] = useState('')
  const [status, setStatus] = useState('')
  const [page, setPage] = useState(1)
  useEffect(() => setItems(readCertificationTemplates()), [])
  const saveAll = (next: CertificationTemplate[]): void => { setItems(next); saveCertificationTemplates(next) }
  const filtered = useMemo(() => items.filter(item => (!search || [item.name, item.equipment, item.equipmentBrand].some(value => value.toLowerCase().includes(search.toLowerCase()))) && (!status || (status === 'active' ? item.active : !item.active))), [items, search, status])
  const pages = Math.max(1, Math.ceil(filtered.length / 7))
  const visible = filtered.slice((page - 1) * 7, page * 7)
  return <AdminGuard permission='academic.manage'><Head><title>Biblioteca de certificaciones | HM</title></Head><Flex className='course-management-heading' justify='between' align='end'><Box><Text as='h1' css={{ fontSize: '$7' }}>Biblioteca de certificaciones</Text><Text css={{ color: '$shade300' }}>Plantillas reutilizables con los datos que se imprimen en cada certificado.</Text></Box><button className='admin-primary-button' onClick={() => setEditing(empty())}>+ Crear certificación</button></Flex><Box className='access-table-panel'><Box className='access-filters certification-library-filters'><input value={search} onChange={event => { setSearch(event.target.value); setPage(1) }} placeholder='Buscar certificación, equipo o marca…' /><select value={status} onChange={event => { setStatus(event.target.value); setPage(1) }}><option value=''>Todos los estados</option><option value='active'>Activas</option><option value='inactive'>Inactivas</option></select></Box><Box className='access-table-scroll'><table className='access-table certification-library-table'><thead><tr><th>Certificación</th><th>Equipo</th><th>Horas</th><th>Marca</th><th>Vigencia</th><th>Estado</th><th /></tr></thead><tbody>{visible.map(item => <tr key={item.id}><td><strong>{item.name}</strong><small className='access-code'>{item.description}</small></td><td>{item.equipment}</td><td><span className='access-count'>{item.hours}</span></td><td>{item.equipmentBrand || 'No aplica / todas'}</td><td>{item.validity}</td><td><span className={item.active ? 'access-status active' : 'access-status inactive'}>{item.active ? 'Activa' : 'Inactiva'}</span></td><td><button className='access-action' onClick={() => setEditing({ ...item })}>Editar →</button></td></tr>)}</tbody></table></Box>{!visible.length && <Box className='access-empty'><strong>Sin certificaciones</strong><p>Cambie los filtros o cree una definición.</p></Box>}<Flex className='access-pagination' justify='between'><Text>Mostrando {visible.length} de {filtered.length}</Text><Flex gap='2' css={{ width: 'auto' }}><button disabled={page === 1} onClick={() => setPage(page - 1)}>Anterior</button><span>Página {page} de {pages}</span><button disabled={page === pages} onClick={() => setPage(page + 1)}>Siguiente</button></Flex></Flex></Box>
  {editing && <Box className='admin-modal access-drawer certification-library-drawer' onClick={() => setEditing(null)}><Box className='admin-modal-card' onClick={event => event.stopPropagation()}><Flex justify='between' align='center'><Box><span>Plantilla reutilizable</span><Text as='h2'>Datos del certificado</Text><Text css={{ color: '$shade300', fontSize: '$2' }}>Estos valores estarán disponibles para emitir e imprimir certificados.</Text></Box><button className='drawer-close' onClick={() => setEditing(null)}>×</button></Flex><Box className='certification-library-form'><label className='admin-field'>Nombre de la plantilla *<input value={editing.name} onChange={event => setEditing({ ...editing, name: event.target.value })} placeholder='Ej. Certificación de operación segura' /></label><label className='admin-field'>Equipo *<input value={editing.equipment} onChange={event => setEditing({ ...editing, equipment: event.target.value })} placeholder='Ej. Montacargas contrabalanceada' /></label><Box className='certification-template-grid'><label className='admin-field'>Horas de capacitación *<input type='number' min='1' value={editing.hours} onChange={event => setEditing({ ...editing, hours: Number(event.target.value) })} /></label><label className='admin-field'>Marca del equipo (si aplica)<input value={editing.equipmentBrand} onChange={event => setEditing({ ...editing, equipmentBrand: event.target.value })} placeholder='Todas las marcas' /></label></Box><label className='admin-field'>Uso limitado por<input value={editing.limitedUse} onChange={event => setEditing({ ...editing, limitedUse: event.target.value })} placeholder='Ej. Empresa o sede autorizada' /></label><label className='admin-field'>Caducidad / vigencia<input value={editing.validity} onChange={event => setEditing({ ...editing, validity: event.target.value })} placeholder='Ej. 1 año' /></label><label className='admin-field'>Información de contacto<textarea rows={3} value={editing.contactInfo} onChange={event => setEditing({ ...editing, contactInfo: event.target.value })} placeholder='Teléfono, correo o sitio web' /></label><label className='admin-field'>Descripción interna<textarea rows={3} value={editing.description} onChange={event => setEditing({ ...editing, description: event.target.value })} /></label><label className='admin-check'><input type='checkbox' checked={editing.active} onChange={event => setEditing({ ...editing, active: event.target.checked })} /> Plantilla activa</label></Box><Flex className='quote-send-footer' justify='end' gap='3'><button className='admin-secondary-button' onClick={() => setEditing(null)}>Cancelar</button><button className='admin-primary-button' disabled={!editing.name.trim() || !editing.equipment.trim() || editing.hours <= 0} onClick={() => { saveAll(items.some(item => item.id === editing.id) ? items.map(item => item.id === editing.id ? editing : item) : [...items, editing]); setEditing(null) }}>Guardar plantilla</button></Flex></Box></Box>}</AdminGuard>
}
Page.getLayout = (page: ReactElement) => <AdminShell>{page}</AdminShell>
export default Page
